replicaCount: 1

image:
  repository: sarahghabri/moderation-worker
  tag: "11"
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  - name: KAFKA_BROKER
    value: "kafka:9092"
  - name: KAFKA_CLIENT_ID
    value: "moderation-worker-1"
  - name: KAFKA_GROUP_ID
    value: "moderation-group"
  - name: CLASSIFICATION_SERVICE_URL
    value: "classification-service:50051"
  - name: NODE_ENV
    value: "production"
